kumuluzee:
  name: vehicle-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/VEHICLE-DS
      connection-url: jdbc:postgresql://localhost:5432/microserviceDB
      username: postgres
      password: docker
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/VEHICLE-DS
    metrics:
      web-instrumentation:
        - name: images-endpoint
          url-pattern: /v1/vehicles/*

  config:
    consul:
        agent: 'http://localhost:8500'

rest-properties:
  maintenance-mode: false
